### ISSUE TITLE
Consider flow routing of nonuniform initial depth without rainfall - why isn't it spreading out

### ISSUE THREAD

**Issue by dvalters** [dvalters/HAIL-CAESAR#10]
@aproeme's inital results showed that when a non-uniform water grid was imposed at the start of the simulation, this would not 'equalise' out over the domain as might be intuitively expected. This could be to do with the `edgeslope` or with unusual idealised case of routing algorithm being applied to a topography surface where all the heights are = 0.

**Comment by aproeme** [comment]
Fixed by 56cd4ac
