### ISSUE TITLE
how to generate the DEM input files(.asc)

### ISSUE THREAD

**Issue by Dongxueyang** [dvalters/HAIL-CAESAR#29]
When I build a new project to make a simulation. I have to write DEM input file as ascii format.
I open the file and see some data about the elevation. 
But I want to know the meaning of the variable such as: ncols, nrows, xllcorner,yllcorner,cellsize,NODATA_value.
And other data is similar about pixel （0-255），is there any connection between the pixel with elevation? 
How can I generate this DEM file?
Can anybody help me?

best regards

dong
dxy159753@sina.com

**Comment by Dongxueyang** [comment]
@dvalters

**Comment by tcoulthard** [comment]
It’s a standard arc-gis ascii format. Google that and you’ll find out what the header contains.

On 4 Aug 2019, at 06:41, Dongxueyang <notifications@github.com<mailto:notifications@github.com>> wrote:


When I build a new project to make a simulation. I have to write DEM input file as ascii format.
I open the file and see some data about the elevation.
But I want to know the meaning of the variable such as: ncols, nrows, xllcorner,yllcorner,cellsize,NODATA_value.
And other data is similar about pixel （0-255），is there any connection between the pixel with elevation?
How can I generate this DEM file?
Can anybody help me?

best regards

dong
dxy159753@sina.com<mailto:dxy159753@sina.com>

**Comment by dvalters** [comment]
@Dongxueyang as Tom says, the header info is a standard format, i.e.: http://resources.esri.com/help/9.3/arcgisengine/java/GP_ToolRef/spatial_analyst_tools/esri_ascii_raster_format.htm

The pixel value should be the elevation (usually in metres) (0-255 almost seems like it is some sort of colour band range, (8-bit colour map would be 256 values...?) but could be coincidental) so check you haven't exported the colour map as the raster by mistake.
