### ISSUE TITLE
Is HAIL-CAESAR can be used for the flood simulation?

### ISSUE THREAD

**Issue by xuhenry** [dvalters/HAIL-CAESAR#30]
Hello, everyone.
     I want to simulate the flood evolution in a river during the process of a dam break. And I know the flow of the dam break.
     Is HAIL-CAESAR can be used for this kind of simulation? And is there any examples about this ?
Thanks a lot!
Best regards,
Henry

**Comment by tcoulthard** [comment]
Henry,
Declan may have an example for HC, but for CAESAR-Lisflood one of the examples where the model is first tested is for a dam break scenario (see Coulthard et al., ESP&L; 2013)
Tom

**Comment by dvalters** [comment]
Hi @xuhenry, I have not tested Hail-Caesar under a dam break scenario, in theory you should see the same results as the paper cited by Tom with CAESAR-Lisflood, unless this is done in reach mode, which HC does not support (yet: see #14)

**Comment by tcoulthard** [comment]
Yes it’s in reach mode in the paper.

On 6 Aug 2019, at 11:22, Declan Valters <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @xuhenry<https://github.com/xuhenry>, I have not tested Hail-Caesar under a dam break scenario, in theory you should see the same results as the paper cited by Tom with CAESAR-Lisflood, unless this is done in reach mode, which HC does not support (yet: see #14<https://github.com/dvalters/HAIL-CAESAR/issues/14>)

**Comment by dvalters** [comment]
Hi @xuhenry I know this is an old issue now, but the current version of Hail-Caesar has a basic Reach Mode implemented in it now, so I'm closing this issue. 
Best wishes, Declan.
